### PR TITLE
Improvements, add teleport option

### PR DESCRIPTION
**Pull request by anzz1**
* add option to teleport user to home (hearthstone location)
* add configurable kick/teleport (can use both). if neither, then it just logs people entering restricted zones.
* don't spam the console and try to kick multiple times even though player is already being kicked

### CODE REVIEW

**Comment by 55Honey** [comment]
Hi anzz1, thanks for your PR.

I have some concerns I'd like to adress:
1) The default state of the teleport config on master would need to be false.

2) Your Check for the Homelocation triggers a sync query. That's a thing which may never happen during runtime, since all eluna queries with Returns are sync queries and halt the whole core until the value was read.
Since a players home location might change at runtime, it's not even possible to read it from the DB at Server start. The only option i can think of, is to expose GetBind() to Eluna and use the function.

3) in lines 120 and 123 you Check for a variable without a value to compare to. That would potentially result in the value being `false` but the If still being true. You probably want to Check for `==true` there.

**Comment by anzz1** [comment]
Hey, and thanks for taking the time to respond in detail. 

Regarding your concerns:
1. Okay, that can be changed.

2. Eluna.CharDBQuery is basically just a wrapper for CharacterDatabase.Query in the core, right? I understand the point of synchronous database queries being done is not great but then I saw these being extensively used in other modules and the core itself so I thought it was "fine". Best way is of course just pulling the value from memory which could be done by exposing the player->m_homebind values in Eluna.

   There is also a Database.AsyncQuery method in the core which pushes the SQL job to the worker thread and result is returned as callback which would be the way to go regarding DB queries.To my surprise it isn't widely used though? Eluna also does not expose this function, but can do a asynchronous query using Execute, but that one cannot return any values. 

   I guess at this point the only option would be to teleport players to a static point like Orgrimmar/Stormwind then. Or redo this module as a regular cpp-module, but that would be shame as I absolutely love the Eluna's concept of drop-in test-immediately never-recompile modules.

3. I don't see this happening as they are defined in the local scope.

**Comment by 55Honey** [comment]
About the config Flflags: If a user declares them as false, the If will still consider the Statement true. Example:

```
n = false
if n then
    Print('1')
end
```
The above prints 1, because n is not nil.

**Comment by 55Honey** [comment]
As for the sync queries, i used them in CarbonCopy and i absolutely had to split them Up, otherwise the core would freeze for 200ms. Yes, the whole core.

The ideal solution would be to add a worker thread to Eluna and Register a timed Event which Checks for returns. But that's way above my head unfortunately.

**Comment by anzz1** [comment]
I checked, and it does not, and should not consider the statement true as per the spec.  So your example does not print 1, nor it should.

Lua spec states that 
`"The type boolean has two values, false and true. Both nil and false make a condition false; they are collectively called false values. Any other value makes a condition true."` https://www.lua.org/manual/5.4/manual.html#2.1

That being said, if n = 0 then if (n) returns true. Using if (n==true) then has the same problem with opposite result, if n=1 then if(n==true) returns false. There is no way around user making that error save for writing a new function comparing it both ways but that would just be stupid. The user must understand that if config flag says false it means that if you want to change it you must set it to true

The ideal solution would be to use the ASyncQuery method in the core, a timed Event won't help in this case. Currently Eluna only has possibility to make a synchronous query which is always blocking. Only Execute runs asynchronously, but it does not return any results.

If something like this would be implemented in Eluna Engine
```
callbackfunc_tbl ={}
function Eluna.ASyncQueryResultsReturned(results, id)
     callbackfunc_tbl[id](results)
end
function Eluna.CharDBASyncQuery(queryString, callbackFunc)
    ... push the query and id of the query to the core database worker thread ...
    callbackfunc_tbl[id] = callbackFunc
end
```

Something like this could be used then in scripts:
```
local function resultsCallback(results)
    if results then
        repeat
            local entry, name = Q:GetUInt32(0), Q:GetString(1)
            print(entry, name)
        until not Q:NextRow()
    else
        print("db fetch failed")
    end
end


local function whatever()
    CharDBASyncQuery("SELECT entry, name FROM creature_template LIMIT 10", resultsCallback)
    -- continue execution as normal, resultsCallback will be called later when results arrive
end
```

**Comment by 55Honey** [comment]
> I checked, and it does not, and should not consider the statement true as per the spec. So your example does not print 1, nor it should.

You're correct, I misremembered this.

I do prefer this more versatile approach though, which requires it: (example from the recruit a friend Lua)
```
-- set to 1 to grant recruits always rested. Any other value including nil turns it off.
Config.grantRested = 1
```

**Comment by anzz1** [comment]
Closed for now

**Comment by anzz1** [comment]
I posted an issue for implementing ASyncQuery to the Eluna repo https://github.com/ElunaLuaEngine/Eluna/issues/403

**Comment by 55Honey** [comment]
How about https://elunaluaengine.github.io/Unit/CastSpell.html and https://wowgaming.altervista.org/aowow/?spell=8690?

Triggered spells are instant and have no cost.

**Comment by anzz1** [comment]
Well that is a great way to do it, and works flawlessly from my testing. I created a new PR to do exactly that https://github.com/55Honey/Acore_Zonecheck/pull/2

**Pull request closed without merging**
